game_columns = [
	'DATE',
	'NUMBER_OF_GAMES',
	'DAY_OF_WEEK',
	'VISITING_TEAM',
	'VISITING_LEAGUE',
	'VISITING_GAME_NUMBER',
	'HOME_TEAM',
	'HOME_LEAGUE',
	'HOME_TEAM_GAME',
	'VISITING_SCORE',
	'HOME_SCORE',
	'OUTS',
	'DAY_NIGHT',
	'COMPLETION',
	'FORFEIT'
	'PROTEST'
	'PARK',
	'ATTENDANCE',
	'LENGTH',
	'VISITING_LINE',
	'HOME_LINE',
]

game_columns = '{
	0 : 'DATE',
	1 : 'NUMBER_OF_GAMES'
}